version: 2
updates:
  - package-ecosystem: gomod
    directory: "."
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: npm
    directory: "./frontend/"
    schedule:
      interval: weekly
      day: monday
