version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: npm
    directory: "links-admin/"
    schedule:
      interval: weekly
      day: monday