services:
  postgres:
    image: postgres:13.12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
  links:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LINKS_PORT=8080
      - LINKS_DB_HOST=hello.com:5438
      - LINKS_DB_USER=user
      - LINKS_DB_PASSWORD=password
