services:
  # db:
  #   image: postgres:alpine3.18
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=hcflinks
  #   ports:
  #     - 9988:5432
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  db:
    image: redis:alpine3.18
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  links:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LINKS_BACKEND=redis
      - LINKS_PORT=8080
      - LINKS_DB_HOST=host.docker.internal
      - LINKS_DB_USER=postgres
      - LINKS_DB_PASSWORD=postgres
      - LINKS_DB_DATABASE=hcflinks
      - LINKS_DB_PORT=9988
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db"