services:
  db:
    image: postgres:13.12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hcflinks
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # links:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
      # - LINKS_BACKEND=postgres
      # - LINKS_PORT=8080
      # - LINKS_DB_HOST=localhost
      # - LINKS_DB_USER=postgres
      # - LINKS_DB_PASSWORD=postgres
      # - LINKS_DB_DATABASE=hcflinks
      # - LINKS_DB_PORT=5442
  #   depends_on:
  #     db:
  #       condition: service_healthy