name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: subdir/go.sum
      - run: cd server
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v server/...
      - name: Test with the Go CLI
        run: go test